import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import vue from '@vitejs/plugin-vue';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/css/frontend.css',
                'resources/js/app.js',
                'resources/js/scripts/frontend.js',
                'resources/js/scripts/script.js',
                'resources/js/scripts/password_status.js',
                'resources/js/scripts/password_status_validation.js',
                'resources/js/scripts/index_script.js',
                'resources/js/scripts/menu.js',
                'resources/js/scripts/role.js',
                'resources/js/scripts/role_permissions.js',
                'resources/css/flatpickr.min.css',
                'resources/js/scripts/flatpickr.min.js',
                'resources/js/scripts/otp.js',
                'resources/js/scripts/region.js',
                'resources/js/scripts/center.js',
                'resources/js/scripts/counter.js',
                'resources/js/scripts/sticker.js',
                 // 'resources/js/scripts/shop.js',
                 'resources/js/scripts/service.js',
               'resources/js/scripts/operator.js',
                'resources/js/scripts/barcodeprint.js',
                 'resources/js/scripts/app_receive.js',
                  'resources/js/scripts/frp_receive.js',
                  'resources/js/scripts/form_fill.js',
                 'resources/js/scripts/moneyReceipt.js',
                 'resources/js/scripts/visaDuration.js',
                 'resources/js/scripts/entryType.js',
                 'resources/js/scripts/receiptprint.js',
                  'resources/js/scripts/fpreceiptprint.js',
                 'resources/js/scripts/send2hci.js',
                'resources/js/scripts/accept4mhci.js',
                'resources/js/scripts/reject4mhci.js',
                'resources/js/scripts/direct4mhci.js',
                'resources/js/scripts/readyCenter.js',
                'resources/js/scripts/centerDelivery.js',
                 'resources/js/scripts/send2MOFA.js',
                'resources/js/scripts/readyCenter.js',
                'resources/js/scripts/biometric.js',
                'resources/js/scripts/digitizationScan.js',
                   'resources/js/scripts/updateStage.js', 
                  'resources/js/scripts/readyDelAct.js',  
                     'resources/js/scripts/webreplace.js',  
               'resources/js/scripts/adminApprove.js',  
               'resources/js/scripts/acceptReject.js',             
                'resources/js/scripts/visatype.js',  
               'resources/js/scripts/holiday.js',    
                'resources/js/scripts/device.js',    
                 'resources/js/scripts/user.js',   
                'resources/js/scripts/recReport.js',  
                'resources/js/scripts/dbquery.js',  
                    'resources/js/scripts/frpRecReport.js',  
                  'resources/js/scripts/overrideReport.js',  
                 'resources/js/scripts/formfillReport.js',  
                  'resources/js/scripts/biometricReport.js',  
                'resources/js/scripts/exceptReport.js',  
                 'resources/js/scripts/tokenReport.js',  
                 'resources/js/scripts/smsReport.js',   
                'resources/js/scripts/actReport.js',   
         		'resources/js/scripts/recSummary.js',   
                'resources/js/scripts/codeUpdate.js',   
                'resources/js/scripts/digitization.js',   
                 'resources/js/scripts/portName.js',   
                 'resources/js/scripts/readyDelDelete.js',   
                  'resources/js/scripts/rejectReport.js',   
                  'resources/js/scripts/reject.js',   
                 'resources/js/scripts/undelReport.js',  
                 'resources/js/scripts/dashboard.js',  
                'resources/css/swiper-bundle.min.css',
                'resources/js/scripts/swiper-bundle.min.js'
            ],
            refresh: true,
        }),
        vue()
    ],
    resolve: {
        alias: {
            vue: 'vue/dist/vue.esm-bundler.js', // ✅ Use the full build of Vue
        },
    },
});
